//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceFeeFormula
    {
        public string ClientCode { get; set; }
        public string AirFareFlag { get; set; }
        public string ServiceFeeFlag { get; set; }
        public string OtherFeeFlag { get; set; }
        public Nullable<decimal> Divide { get; set; }
        public Nullable<decimal> Multiply { get; set; }
    }
}
